book/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('bookstore.urls')),
	path('/', include('bookstore.urls')),
    path('admin/', admin.site.urls),
	path('/admin/', admin.site.urls),
]

# urlpatterns = [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = "bookstore"
urlpatterns = [
	path('/', views.index, name="index_deploy"),
    	path("", views.index, name="index"),
    	path("login", auth_views.LoginView.as_view(template_name="bookstore/login.html"), name="login"),
 	path("/login", auth_views.LoginView.as_view(template_name="bookstore/login.html"), name="login_deploy"),
	path("logout", auth_views.LogoutView.as_view(template_name="bookstore/logout.html"), name="logout"),
    	path("/logout", auth_views.LogoutView.as_view(template_name="bookstore/logout.html"), name="logout_deploy"),
	path("register", views.register, name="register"),
	path("/register", views.register, name="register_deploy"),
	path("search", views.search, name="search"),
	path("/search", views.search, name="search_deploy"),
	path("profile", views.profile, name="profile"),
    	path("/profile", views.profile, name="profile_deploy"),
	path("item/<str:isbn>", views.item, name="item"),
	path("/item/<str:isbn>", views.item, name="item_deploy"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/models.py
import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image

# Create your models here.
class Book(models.Model):
    isbn = models.CharField(max_length=16)      # isbn 13
    title = models.CharField(max_length=512)
    author = models.CharField(max_length=128)
    publish_date = models.CharField(max_length=32)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2)
    ratings_count = models.IntegerField()
    page_count = models.IntegerField()
    description = models.CharField(max_length=int(2**14))


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book =  models.ForeignKey(Book, on_delete=models.CASCADE, related_name="book_comment")
    # timestamp = models.DateTimeField(default=datetime.datetime.now().replace(microsecond=0))
    timestamp = models.DateTimeField(default=timezone.now())
    content = models.CharField(max_length=int(2**14))

        
class Profile(models.Model):
    firstname = models.CharField(max_length=30, blank=True)
    lastname = models.CharField(max_length=30, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='usr')
    # image = models.ImageField(default='default.jpg', upload_to='usr')
    phone = models.CharField(max_length=30, blank=True)


    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        # if img.height > 300 or img.width > 300:
        #     output_size = (300, 300)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)

bookstore/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_texts = {
            "username": None,
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email"]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["firstname", "lastname", "phone", "image"]

bookstore/views.py
import json, itertools, requests
from django.core import serializers
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from bookstore.models import Book, Comment
from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm

def index(request):
    # if not request.user.is_authenticated:
    username = request.user.username
    context = {"username": username}
    return render(request, "bookstore/index.html", context)

def search(request):
    books = None
    if request.method == "POST":
        usr_input = "|".join(request.POST["search"].split())
        # Get results from three different fields by applying regex
        result_1 = Book.objects.filter(title__iregex=str(usr_input))
        result_2 = Book.objects.filter(author__iregex=str(usr_input))
        result_3 = Book.objects.filter(isbn__iregex=str(usr_input))
        
        # Combine and remove duplicate from three result lists
        books = list(set(itertools.chain(result_1, result_2, result_3)))
    else:
        books = Book.objects.all()[:50]
        
    return render(request, "bookstore/search.html", {
        "books": books
    })

def item(request, isbn):
    username = 'anonymous'      # Default username
    book = Book.objects.filter(isbn=isbn)[0]
    if book:
        # Call Google Book api for book cover
        res = requests.get("https://www.googleapis.com/books/v1/volumes", params={"q": "isbn:{}".format(book.isbn)})
        try:
            imgsrc = res.json()['items'][0]['volumeInfo']['imageLinks']['thumbnail']
        except Exception:
            imgsrc = None
            
        # Check and get user's username
        if request.user.is_authenticated:
            username = request.user.username

        # If there is a new comment
        if request.method == "POST":
            new_cmt = Comment(
                user=User.objects.get(username=username),
                book=Book.objects.get(isbn=isbn),
                content=request.POST['content']
            )
            new_cmt.save()
        
        # Get comments on this book
        cmts = Comment.objects.filter(book__isbn__contains=isbn)[::-1]

        context = {"book": book, "imgsrc": imgsrc, "cmts": cmts, "username": username}
        return render(request, "bookstore/item.html", context)
    else:
        return render(request, "bookstore/notfound.html")

def register(request):
    form = CreateUserForm()

    if request.method == "POST":
        form =CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            # messages.success(request, f'Account created for {username}!')
            return redirect("/login")
        # else:
        #     messages.info(request, "Username or password is in correct")
    else:
        form = CreateUserForm()
    context = {"form":form}
    return render(request, "bookstore/register.html", context)

@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect("/profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, "bookstore/profile.html", context)
    

# Login page
# def loginPage(request):
#     #form = AuthenticationForm()
#     if request.method == "POST":
#         username = request.POST.get("username")
#         password = request.POST.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect(reverse('bookstore:index'))
#         else:
#             return render (request, "bookstore/login.html")

#     return render (request, "bookstore/login.html")

# def logoutPage(request):
#     return render(request, "bookstore/logout.html")

bookstore/templates/bookstore/index.html
{% extends "bookstore/layout.html" %}

{% block styles %}
    <link rel="stylesheet" href="https://raw.githubusercontent.com/icesonata/Mybrary/main/bookstore/static/bookstore/styles/index.css">
{% endblock %}

{% block title %}
    Mybrary
{% endblock %}

{% block body %}
    <!-- <h1 class="cover-heading">Online Book Station</h1> -->
    <div class="container">
        <p class="lead motto">
            The world of reading where you can find the most exciting book <br> while connecting and sharing your thought with others 
        </p>
        <p class="lead">
            <a class="btn btn-lg btn-secondary" href="{% url 'bookstore:search' %}" >Find your own book</a>
        </p>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

bookstore/templates/bookstore/item.html
{% extends "bookstore/layout.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'bookstore/styles/item.css' %}">
<style>
.main-pane {
    border: 3px solid grey;
    background-color: white;
    width: 100%;
    /* width: 900px; */
    padding: 20px 40px 20px 20px;
    /* height: 500px; */
    color: rgb(42, 42, 42);
    border-radius: 10px;
    margin-bottom: 10px;
}

/* Navigation */
/* .main-pane > a {
    color: black;
    font-weight: bold;
    text-align: left;
    margin: 0 0 30px 0;
} */

/* Resize the book's cover */
.cover > img {
    width: 160px;
    height: 250px;
}

/* Comment section */
.form-comment {
    /* display: flex; */
    margin: 0px 0px 20px 0px ;
    text-align: right;
}

.form-comment textarea {
    width: 100%;
    height: 120px;
    border-radius: 5px;
    border: 2px solid grey;
    padding: 0px 40px;
    /* right: 0px; */
}

.form-comment textarea:focus {
    /* box-shadow: 0 0 2pt 2pt black; */
    outline: none;
}

.form-comment button {
    border-radius: 5px;
    background-color: rgb(0, 79, 191);
    border: 2px solid rgb(0, 79, 191);
    padding: 0px 20px;
    font-weight: bold;
    color: white;
    height: 40px;
    
    /* float: right; */
    /* margin: 0 0 20px 0; */
    /* margin-left: 40px; */
}

.form-comment button:hover {
    cursor: pointer;
}

#input-username {
    border-radius: 5px;
    margin: 0 0 0 10px;
}

.form-comment > label, #input-username {
    float: left;
}

/* ::-webkit-input-placeholder {
    text-align: center;
    vertical-align:text-bottom;
} */

.user-avatar {
    margin: 0 10px 20px 10px;
    text-align: center;
    width: 5em;
    height: 5em;
}

.user-avatar > img {
    height: 100px;
    width: 100px;
    border-radius: 100px;
}

.comment {
    border: 2px solid grey;
    border-radius: 5px;
    width: 100%;
    /* height: 100px; */
    padding: 20px;
    margin: 10px 0 10px 0;
}

.cmt-username, .cmt-username:hover {
    text-decoration: none;
    color: blue;
}

.timestamp {
    text-align: right;
    float: right; /* put timestamp in the same line of username */
}
</style>
{% endblock %}

{% block title %}
    {{ book.title }}
{% endblock %}

{% block body %}
    <div class="main-pane">
        <!-- <a class="nav" href="{{request.META.HTTP_REFERER}}">< Back to search</a> -->
        <div class="book-info">
            <div class="row">
                <div class="col-3">
                    <div class="cover">
                        <img src="{{ imgsrc }}" alt="{{ book.title }}"/>
                    </div>
                </div>
                <div class="col-9">
                    <h1>{{ book.title }}</h1>
                    <p style="text-align: justify;">
                        <b>ISBN</b>:            {{ book.isbn }}<br>
                        <b>AUTHOR</b>:          {{ book.author }}<br>
                        <b>PUBLISHED DATE</b>:  {{ book.publish_date }}<br>
                        <b>AVERAGE RATING</b>:  {{ book.average_rating }}<br>
                        <b>RATINGS COUNT</b>:   {{ book.ratings_count }}<br>
                        <b>DESCRIPTION</b>:     {{ book.description }}<br>
                    </p>
                </div>
            </div>
        </div>

        <!-- Comment section -->
        <p><i>Comment section:</i></p>
        <form class="form-comment" action="{% url 'bookstore:item' isbn=book.isbn %}" method="post">            
            {% csrf_token %}
            <textarea id="" name="content" rows="4" cols="50" placeholder="Write your thought about this book.."></textarea>
            <label for="username"><b>Username: </b></label>
            <input id="input-username" type="text" name="input-username" value="{{username|default:'anonymous'}}" readonly disabled>
            <button type="submit">Send</button>
        </form>

        <div class="container-comments">
            {% for cmt in cmts %}
                <div class="comment">
                    <div class="row">
                        <div class="col-2">
                            <div class="user-avatar" style="text-align: center;">
                                {% if cmt.user.profile.image.url %}
                                    <img src="{{ cmt.user.profile.image.url }}" alt="{{ user.username }}'s avatar">
                                {% else %}
                                    <!-- Default icon for anonymous user -->
                                    <!-- <i class="fas fa-user-circle fa-5x"></i> -->
                                    
                                    <!-- Default avatar for anonymous user -->
                                    <img src="{% static 'bookstore/media/default.png' %}" alt="anonymous's avatar">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-10">
                            <a class="cmt-username" href="#">{{ cmt.user }}</a>
                            <div class="timestamp">
                                <i>{{cmt.timestamp|date:"H:i:s, d/m/Y"}}</i>
                            </div>
                            <br>
                            <p style="text-align: justify;">
                                {{ cmt.content }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <!-- Sample comment -->
            <!-- <div class="comment">
                <div class="row">
                    <div class="col-2">
                        <div class="user-avatar" style="text-align: center;">
                            <i class="fas fa-user-circle fa-5x"></i>
                        </div>
                    </div>
                    <div class="col-10">
                        <a class="username" href="#" style="color: blue;">adminadminadminadminadminadminadminadminadminadmin</a>
                        <div class="timestamp" style="float: right;">
                            <i>
                                17:14:53,
                                08-03-2021
                            </i>
                        </div>
                        <br>
                        <p style="text-align: justify;">
                            NO SAFE PLACE LEFT At great cost to the Garrison and the Survey Corps, Commander Erwin has managed to recover Eren from the Titans who tried to carry him off. But during the battle, Eren manifested yet another power he doesn't understand. As Eren and Krista find new enemies, the Survey Corps faces threats from both inside and outside the walls. And what will happen to Ymir, now that she has decided to make herself the Titans' prize?
                        </p>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
    
{% endblock %}

{% block scripts %}
    <script defer src="{% static 'bookstore/scripts/item.js' %}"></script>
{% endblock %}

bookstore/templates/bookstore/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- Import external script files -->
        <script defer src="{% static 'bookstore/scripts/layout.js' %}"></script>
        {% block scripts %}{% endblock %}

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <!-- Custom file for this page -->
        <link rel="stylesheet" href="{% static 'bookstore/styles/layout.css' %}">
        
        <!-- Import external style files -->
        {% block styles %}{% endblock %}
        
        <!-- Create title -->
        <title>{% block title %}{% endblock %}</title>
        
        <!-- Bootstrap core JavaScript -->
        <script defer src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!-- Fontawesome core JavaScript -->
        <script defer src="https://kit.fontawesome.com/bba29906f3.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
            <header class="masthead mb-auto">
              <div class="inner">
                <h2 class="masthead-brand"><a class="brand-logo" href="{% url 'bookstore:index' %}" style="text-decoration:none">Mybrary</a></h3>
                <nav class="nav nav-masthead justify-content-center">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'bookstore:profile' %}">Profile</a>
                    <a class="nav-link" href="{% url 'bookstore:logout' %}">Logout</a>
                  {% else %}
                  <!-- <a class="nav-link active" href="#">Login</a> -->
                    <a class="nav-link" href="{% url 'bookstore:login' %}">Login</a>
                    <a class="nav-link" href="{% url 'bookstore:register' %}">Register</a>
                  {% endif %}
                </nav>
              </div>
            </header>
      
            <main role="main" class="inner cover">
              {% block body %}{% endblock %}
            </main>
      
            <footer class="mastfoot mt-auto">
                <div class="inner">
                    <p id="template_author">Edit and custom by <a href="https://github.com/icesonata">@icesonata</a> and <a href="https://github.com/18521184">@18521184</a></p>
                </div>
            </footer>
          </div>
    </body>
</html>

<!--
    Cover template for Bootstrap by @mdo
    Src: https://getbootstrap.com/docs/4.0/examples/cover/
-->

bookstore/templates/bookstore/layout_cp.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- Import external script files -->
        {% block scripts %}{% endblock %}

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <!-- Custom file for this page -->
        <link rel="stylesheet" href="https://raw.githubusercontent.com/icesonata/Mybrary/main/bookstore/static/bookstore/styles/layout.css">
        
        <!-- Import external style files -->
        {% block styles %}{% endblock %}
        
        <!-- Create title -->
        <title>{% block title %}{% endblock %}</title>
        
        <!-- Bootstrap core JavaScript -->
        <script defer src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!-- Fontawesome core JavaScript -->
        <script defer src="https://kit.fontawesome.com/bba29906f3.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
            <header class="masthead mb-auto">
              <div class="inner">
                <h2 class="masthead-brand"><a class="brand-logo" href="{% url 'bookstore:index' %}" style="text-decoration:none">Mybrary</a></h3>
                <nav class="nav nav-masthead justify-content-center">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'bookstore:profile' %}">Profile</a>
                    <a class="nav-link" href="{% url 'bookstore:logout' %}">Logout</a>
                  {% else %}
                  <!-- <a class="nav-link active" href="#">Login</a> -->
                    <a class="nav-link" href="{% url 'bookstore:login' %}">Login</a>
                    <a class="nav-link" href="{% url 'bookstore:register' %}">Register</a>
                  {% endif %}
                </nav>
              </div>
            </header>
      
            <main role="main" class="inner cover">
              {% block body %}{% endblock %}
            </main>
      
            <footer class="mastfoot mt-auto">
                <div class="inner">
                    <p id="template_author">Edit and custom by <a href="https://github.com/icesonata">@icesonata</a> and <a href="https://github.com/18521184">@18521184</a></p>
                </div>
            </footer>
          </div>
    </body>
</html>

<!--
    Cover template for Bootstrap by @mdo
    Src: https://getbootstrap.com/docs/4.0/examples/cover/
-->

bookstore/templates/bookstore/login.html
{% extends "bookstore/layout.html" %}
{% load static %}

{% block styles %}
    <style>
        form {
            text-align: center;
        }
        label {
            width: 100px;
        }
        button {
            width: 220px;
            margin-left: 110px;
            text-align: left;
        }
    </style>
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</leSgend>
            </fieldset>
            <div class="form-group">
                <label for="username">Username: </label>
                <input type="text" name="username" placeholder="Username">
                <br>
                <label for="password">Password: </label>
                <input type="password" name="password" placeholder="Password">
                <br>
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Not a member? <a class="ml-2" href="register">Sign up now</a>
            </small>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

bookstore/templates/bookstore/logout.html
{% extends "bookstore/layout.html" %}
{% load static %}

{% block styles %}
{% endblock %}

{% block title %}
{% endblock %}

{% block body %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="login">Log in again</a>
        </small>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

bookstore/templates/bookstore/search.html
{% extends "bookstore/layout.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'bookstore/styles/search.css' %}">
<style>
html {
    scroll-behavior: auto;
}

.search-bar {
    display: flex;
    position: absolute;
    top: 15%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.search-bar input {
    width: 800px;
    height: 42px;
    border-radius: 50px;
    border: 2px solid grey;
    padding: 0px 40px;
    right: 0px;
}

.search-bar input:focus {
    box-shadow: 0 0 2pt 2pt white;
    outline: none;
}

.search-bar button {
    border-radius: 50%;
    background-color: transparent;
    border: none;
    padding: 0px 10px;
    margin-left: -40px;
}

.search-bar button:hover {
    cursor: pointer;
}

.message {
    text-align: center;
    font-weight: bold;
}

.list-item {
    position: absolute;
    width: 800px;
    border-radius: 10px;
    background-color: white;
    color: rgb(62, 62, 62);
    top: 35%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding: 10px;
    margin: 150px auto auto auto;

    border: 10px solid white;
    border-right: transparent;
    height: 510px;
    overflow: auto;
}

.list-item > .item {
    color: rgb(62, 62, 62);
    text-decoration: none;
    border-radius: 10px;
    background-color: white;
    border: 2px solid black;
    padding: 10px;
    margin: 5px 0px 5px -5px;
    cursor: pointer;

    display: block;     /* Make a element as div block */
}

.list-item > .item:hover {
    box-shadow: 0 0 2pt 2pt black;
}

/* Customize scroll bar */
/* width */
::-webkit-scrollbar {
    width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
    box-shadow: inset 0 0 1px black; 
    border-radius: 10px;
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: rgb(145, 136, 136); 
    border-radius: 10px;
    height: 20%;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
    background: rgb(47, 47, 47); 
}
</style>
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <form class="search-bar" action="{% url 'bookstore:search' %}" method="post">            
        {% csrf_token %}
        <input id="query-string" type="text" name="search" placeholder="Search for book title, author, ISBN..">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>

    <div class="list-item">
        {% if books %}
            {% for book in books %}
                <a class="item" data-isbn="{{ book.isbn }}" href="{% url 'bookstore:item' isbn=book.isbn %}">
                    <b>Title</b>: {{ book.title }}
                    <br>
                    <b>Author</b>: {{ book.author }}
                    <br>
                    <b>ISBN</b>: {{ book.isbn }}
                </a>
            {% endfor %}
        {% else %}
            <p class="message">Item not found</p>
        {% endif %}

        <!-- Sample -->
        <!-- <div class="item" data-isbn="9780765396143">
            Title: Chronicle of the Unhewn Throne: (The Emperor's Blades, The Providence of Fire, The Last Mortal Bond)
            <br>
            Author: Brian Staveley
            <br>
            ISBN: 9780765396143
        </div>

        <div class="item" data-isbn="9780765396143">
            Title: Chronicle of the Unhewn Throne: (The Emperor's Blades, The Providence of Fire, The Last Mortal Bond)
            <br>
            Author: Brian Staveley
            <br>
            ISBN: 9780765396143
        </div> -->
    </div>
{% endblock %}

{% block scripts %}
    <script defer src="{% static 'bookstore/scripts/search.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
//     // Direct user to item info page
//     document.querySelectorAll('.item').forEach(element => {
//         element.onclick = () => {
//             location.href = "/item/" + element.dataset.isbn;
//         }
//     });

    // Append query string to the URL before submitting
    document.querySelector(".search-bar").onsubmit = function() {
        var query = `?q=${this.querySelector('#query-string').value}`;
        var curURL = this.getAttribute('action');
        this.setAttribute('action', curURL + query);
    };
});
</script>
{% endblock %}